name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull Docker image
        run: docker pull jivagoaffonso/somativa2

      - name: Run Docker container
        run: docker run -d -p 80:80 jivagoaffonso/somativa2

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 teste.py
      - uses: AppThreat/sast-scan-action@master
        with:
          entrypoint: nginx
          cmd: -g daemon off;
          image: my-image
          output: result.json

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
